# Your Name or Company
title: Ömer Kuzur

# Description of your website. This is used for social sharing.
description:  Ömer Kuzur Blog

# A brief blurb about yourself
content: Computer Engineer

# Add your social links
social:
  - platform: github
    url: https://github.com/omerkuzur
  - platform: twitter
    url: https://twitter.com/omerkuzur
  - platform: linkedin
    url:  https://linkedin.com/in/omerkuzur


markdown: kramdown
sharing_image: share.jpg
google_analytics: "UA-58263416-1" # google analytics tracking

#### LAYOUT OPTIONS #####

# Half layout
half_side: right

# Full layout
full_text_position: right # left, right or center
